export const TEST_IDS = {
  auth: {
    signInButton: 'auth.sign_in.button',
    verifyCodeButton: 'auth.verify_code.button',
    resendCodeButton: 'auth.resend_code.button',
  },
  account: {
    apiBaseInput: 'account.api_base.input',
    syncBackendButton: 'account.sync_backend.button',
    checkHealthButton: 'account.check_health.button',
    refreshPushDevicesButton: 'account.refresh_push_devices.button',
    revokePushDeviceButton: 'account.revoke_push_device.button',
    signOutButton: 'account.sign_out.button',
  },
  capture: {
    transcriptInput: 'capture.transcript.input',
    startListeningButton: 'capture.start_listening.button',
    stopListeningButton: 'capture.stop_listening.button',
    parseVoiceButton: 'capture.parse_voice.button',
    confirmVoiceButton: 'capture.confirm_voice.button',
    rewardsButton: 'capture.rewards.button',
    receiptCameraButton: 'capture.receipt.camera.button',
    receiptGalleryButton: 'capture.receipt.gallery.button',
    parseReceiptButton: 'capture.parse_receipt.button',
    confirmReceiptButton: 'capture.confirm_receipt.button',
  },
  ledger: {
    refreshButton: 'ledger.refresh.button',
  },
  reports: {
    loadButton: 'reports.load.button',
  },
  rewards: {
    refreshButton: 'rewards.refresh.button',
    redeemPrimaryButton: 'rewards.redeem.primary.button',
  },
  families: {
    loadButton: 'families.load.button',
    nameInput: 'families.name.input',
    createButton: 'families.create.button',
    inviteCodeInput: 'families.invite_code.input',
    joinButton: 'families.join.button',
    createInviteButton: 'families.create_invite.button',
    memberIdInput: 'families.member_id.input',
    updateRoleButton: 'families.update_role.button',
    removeMemberButton: 'families.remove_member.button',
  },
  splits: {
    expenseIdInput: 'splits.expense_id.input',
    titleInput: 'splits.title.input',
    sharedChargeInput: 'splits.shared_charge.input',
    memberIdsInput: 'splits.member_ids.input',
    guestNamesInput: 'splits.guest_names.input',
    createButton: 'splits.create.button',
    loadButton: 'splits.load.button',
    activeSplitIdInput: 'splits.active_split_id.input',
    loadDetailButton: 'splits.load_detail.button',
    saveParticipantsButton: 'splits.save_participants.button',
    assignmentsInput: 'splits.assignments.input',
    saveAllocationsButton: 'splits.save_allocations.button',
    finalizeButton: 'splits.finalize.button',
    loadBalancesButton: 'splits.load_balances.button',
  },
  prices: {
    itemInput: 'prices.item.input',
    locationRefreshButton: 'prices.location.refresh.button',
    locationAreaInput: 'prices.location.area.input',
    includePromoSwitch: 'prices.include_promo.switch',
    compareButton: 'prices.compare.button',
    historyButton: 'prices.history.button',
    signalButton: 'prices.signal.button',
    signalNotifyButton: 'prices.signal_notify.button',
    promoCameraButton: 'prices.promo.camera.button',
    promoGalleryButton: 'prices.promo.gallery.button',
    promoIngestButton: 'prices.promo.ingest.button',
    promoListButton: 'prices.promo.list.button',
  },
  alerts: {
    createButton: 'alerts.create.button',
    loadAlertsButton: 'alerts.load.button',
    loadEventsButton: 'alerts.events.load.button',
    markAllReadButton: 'alerts.events.mark_all_read.button',
  },
} as const;
